databases:
  - name: saferoads_project
    databaseName: saferoads_db_fv2z
    user: saferoads_user
    region: Oregon

services:
  - type: web
    name: saferoads_project
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saferoads_project
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2